version: '3'
services:
  # Frontend (React)
  web: 
    build: 
      context: . # Where we want files/folders pulled from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  # Frontend (React Tests)
  tests:
    build: 
      context: . # Where we want files/folders pulled from
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]